"""add category table

Revision ID: de70d744236a
Revises: dbe8b671c745
Create Date: 2026-05-02 12:43:00.353094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'de70d744236a'
down_revision: Union[str, Sequence[str], None] = 'dbe8b671c745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('name')
    )
    op.add_column('products', sa.Column('category_uid', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'products', 'categories', ['category_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'category_uid')
    op.drop_table('categories')
    # ### end Alembic commands ###
