"""add is admin field

Revision ID: 75b608fec7a7
Revises: a71994ae5fa4
Create Date: 2026-04-24 13:46:55.464128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '75b608fec7a7'
down_revision: Union[str, Sequence[str], None] = 'a71994ae5fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_users', 'is_admin')
    # ### end Alembic commands ###
