"""init orders

Revision ID: 2297928a9ec2
Revises: 
Create Date: 2026-04-01 13:04:43.079034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2297928a9ec2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('order_uid', sa.UUID(), nullable=False),
    sa.Column('product_uid', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('price_snapshot', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_order_items_order_uid'), 'order_items', ['order_uid'], unique=False)
    op.create_index(op.f('ix_order_items_product_uid'), 'order_items', ['product_uid'], unique=False)
    op.create_table('orders',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('user_uid', sa.UUID(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_orders_user_uid'), 'orders', ['user_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_user_uid'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_order_items_product_uid'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_uid'), table_name='order_items')
    op.drop_table('order_items')
    # ### end Alembic commands ###
