"""add product name to orders

Revision ID: 43470be6e7b7
Revises: 2297928a9ec2
Create Date: 2026-05-03 11:22:08.452525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '43470be6e7b7'
down_revision: Union[str, Sequence[str], None] = '2297928a9ec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('product_name', sa.VARCHAR(), nullable=False, server_default='Unknown'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'product_name')
    # ### end Alembic commands ###
