"""init inventory

Revision ID: d18ea9317136
Revises: 
Create Date: 2026-03-29 11:17:15.978211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd18ea9317136'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('product_uid', sa.UUID(), nullable=False),
    sa.Column('available_quantity', sa.INTEGER(), nullable=False),
    sa.Column('reserved_quantity', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.CheckConstraint('available_quantity >= 0', name='check_available_non_negative'),
    sa.CheckConstraint('reserved_quantity >= 0', name='check_reserved_non_negative'),
    sa.PrimaryKeyConstraint('product_uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    # ### end Alembic commands ###
