"""init cart

Revision ID: 3608227d352a
Revises: 
Create Date: 2026-03-31 15:28:25.756686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3608227d352a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_items',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('cart_uid', sa.UUID(), nullable=False),
    sa.Column('product_uid', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_cart_items_cart_uid'), 'cart_items', ['cart_uid'], unique=False)
    op.create_index(op.f('ix_cart_items_product_uid'), 'cart_items', ['product_uid'], unique=False)
    op.create_table('carts',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('user_uid', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_carts_user_uid'), 'carts', ['user_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carts_user_uid'), table_name='carts')
    op.drop_table('carts')
    op.drop_index(op.f('ix_cart_items_product_uid'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_cart_uid'), table_name='cart_items')
    op.drop_table('cart_items')
    # ### end Alembic commands ###
