"""add category table

Revision ID: 0cda508e9974
Revises: 2a70750cabf2
Create Date: 2026-05-02 12:42:27.827433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0cda508e9974'
down_revision: Union[str, Sequence[str], None] = '2a70750cabf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed_products', sa.Column('category_uid', sa.UUID(), nullable=True))
    op.add_column('feed_products', sa.Column('category_name', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed_products', 'category_name')
    op.drop_column('feed_products', 'category_uid')
    # ### end Alembic commands ###
