"""add image url

Revision ID: 2a70750cabf2
Revises: 6d954bdd472c
Create Date: 2026-04-24 12:38:21.444012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2a70750cabf2'
down_revision: Union[str, Sequence[str], None] = '6d954bdd472c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed_products', sa.Column('image_url', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed_products', 'image_url')
    # ### end Alembic commands ###
